//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PingPlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PingPlugin.Properties.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese.
        /// </summary>
        internal static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click through plugin windows.
        /// </summary>
        internal static string ClickThrough {
            get {
                return ResourceManager.GetString("ClickThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defaults.
        /// </summary>
        internal static string Defaults {
            get {
                return ResourceManager.GetString("Defaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide errors.
        /// </summary>
        internal static string HideErrors {
            get {
                return ResourceManager.GetString("HideErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide overlays during cutscenes.
        /// </summary>
        internal static string HideOverlaysDuringCutscenes {
            get {
                return ResourceManager.GetString("HideOverlaysDuringCutscenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        internal static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock plugin windows.
        /// </summary>
        internal static string LockPluginWindows {
            get {
                return ResourceManager.GetString("LockPluginWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal display.
        /// </summary>
        internal static string MinimalDisplay {
            get {
                return ResourceManager.GetString("MinimalDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor Color.
        /// </summary>
        internal static string MonitorColor {
            get {
                return ResourceManager.GetString("MonitorColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor Error Color.
        /// </summary>
        internal static string MonitorErrorColor {
            get {
                return ResourceManager.GetString("MonitorErrorColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor Opacity.
        /// </summary>
        internal static string MonitorOpacity {
            get {
                return ResourceManager.GetString("MonitorOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorded Pings.
        /// </summary>
        internal static string RecordedPings {
            get {
                return ResourceManager.GetString("RecordedPings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Window Positions.
        /// </summary>
        internal static string ResetWindowPositions {
            get {
                return ResourceManager.GetString("ResetWindowPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        internal static string UIAverage {
            get {
                return ResourceManager.GetString("UIAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        internal static string UIError {
            get {
                return ResourceManager.GetString("UIError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Latency (ms) vs Pings.
        /// </summary>
        internal static string UIGraphTitle {
            get {
                return ResourceManager.GetString("UIGraphTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms.
        /// </summary>
        internal static string UIMillisecondAbbr {
            get {
                return ResourceManager.GetString("UIMillisecondAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping: {0}ms / Average: {1}ms.
        /// </summary>
        internal static string UIMinimalDisplay {
            get {
                return ResourceManager.GetString("UIMinimalDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to display at this time..
        /// </summary>
        internal static string UINoData {
            get {
                return ResourceManager.GetString("UINoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to: {0}
        ///Ping: {1}ms
        ///Average ping: {2}ms.
        /// </summary>
        internal static string UIRegularDisplay {
            get {
                return ResourceManager.GetString("UIRegularDisplay", resourceCulture);
            }
        }
    }
}
